package com.hsp.houserent.view;


import com.hsp.houserent.domain.House;
import com.hsp.houserent.service.HouseService;
import com.hsp.houserent.utils.Utility;

/**
 * 1. 显示界面
 * 2. 接收用户的输入
 * 3. 调用HouseService完成对房屋信息的各种操作
 */
public class HouseView {
    private boolean loop = true;
    private char key =' ';
    private HouseService houseService = new HouseService(10);


    public void updateHouse(){
        System.out.println("=============== Change House info ===============");
        System.out.println("Please enter the id that you want to change(-1 to quit)");
        int updateId = Utility.readInt();
        if(updateId == -1){
            System.out.println("quit update");
            return;
        }

        House house = houseService.find(updateId);
        if(house == null){
            System.out.println("id DNE, cannot change");
            return;
        }
        System.out.print("Name("+house.getName()+"): ");
        String name = Utility.readString(8,"");
        if(!"".equals(name)){
            house.setName(name);
        }
        System.out.print("Phone("+house.getPhone()+"): ");
        String phone = Utility.readString(10,"");
        if(!"".equals(phone)){
            house.setPhone(phone);
        }

        System.out.print("Address("+house.getAddress()+"): ");
        String address = Utility.readString(10,"");
        if(!"".equals(address)){
            house.setAddress(address);
        }

        System.out.print("Rent("+house.getRent()+"): ");
        int rent = Utility.readInt(-1);
        if(rent!=-1){
            house.setRent(rent);
        }

        System.out.print("Status("+house.getState()+"): ");
        String state = Utility.readString(10,"");
        if(!"".equals(state)){
            house.setState(state);
        }
        System.out.println("================= Success change ===================");





    }

    public void exit(){
        char c = Utility.readConfirmSelection();
        if(c=='Y'){
            loop = false;
        }

    }

    public void findHouse(){
        System.out.println("Enter the id you want to search:");
        int findId = Utility.readInt();
        House house = houseService.find(findId);
        if(house!=null){
            System.out.println(house);
        }else{
            System.out.println("Id DNE");
        }


    }
    public void delHouse(){
        System.out.println("================ Delete House ====================");
        System.out.print("Enter the house id you want to delete(-1 to exit): ");
        int delId = Utility.readInt();
        if(delId == -1){
            System.out.println("You quit delete");
            return;
        }

        char choice = Utility.readConfirmSelection();
        if(choice == 'Y'){
            if (houseService.del(delId)){
                System.out.println("================ Success Delete ==================");
            }else{
                System.out.println(" =================== id DNE, cannot delete ==============");
            }

        }else{
            System.out.println("You quit delete");
        }

    }



    public void addHouse(){
        System.out.println("=============== Add House =====================");
        System.out.print("Name: ");
        String name = Utility.readString(8);
        System.out.print("Phone: ");
        String phone = Utility.readString(12);
        System.out.print("Address: ");
        String address = Utility.readString(16);
        System.out.print("Rent: ");
        int rent = Utility.readInt();
        System.out.print("Status: ");
        String status = Utility.readString(10);

//        create new House obj, id is automatically generated by system
        House house = new House(0, name, phone, address, rent, status);
        if(houseService.add(house)){
            System.out.println("==================== Success Added ======================");
        }else{
            System.out.println("===================== Fail to add ========================");
        }


    }

    public void listHouses(){
        System.out.println("======================= House List ======================");
        System.out.println("编号\t\t房主\t\t电话\t\t地址\t\t月租\t\t状态(未出租/已出租)");
        House[] houses = houseService.list();
        for(int i=0;i<houses.length;i++){
            if(houses[i] == null){
                break;
            }
            System.out.println(houses[i]);
        }
        System.out.println("==================== House List Displayed==================\n");


    }

//    display menu
    public void mainMenu(){
        do{
            System.out.println("===================House Rent System====================");
            System.out.println("\t\t\t1 Add House Info");
            System.out.println("\t\t\t2 Search House Info");
            System.out.println("\t\t\t3 Delete House Info");
            System.out.println("\t\t\t4 Change House Info");
            System.out.println("\t\t\t5 Display House Info");
            System.out.println("\t\t\t6 Quit");
            System.out.println("Please enter your choice(1-6): ");

            key = Utility.readChar();

            switch (key){
                case '1':
                    System.out.println("Add");
                    addHouse();
                    break;
                case '2':
                    System.out.println("Search");
                    findHouse();
                    break;
                case '3':
                    System.out.println("Delete");
                    delHouse();
                    break;
                case '4':
                    System.out.println("Change");
                    updateHouse();
                    break;
                case '5':
                    System.out.println("Display");
                    listHouses();
                    break;
                case '6':
                    System.out.println("Quit");
                    exit();
                    break;
            }
        }while (loop);

    }
}
